/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package racing.odds.server.app;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;
import racing.odds.server.app.services.MessageUtils;

class MessageUtilsTest {
  @Test
  void testGetMessage() {
    assertEquals("Hello      World!", MessageUtils.getMessage());
  }
}
