version: 2.1

jobs:
  test:
    docker: 
      - image: cimg/node:16.14.0
    steps:
      - checkout
      - run: docker build . | docker container create
      # - run: npm install
      # - run: npm test
workflows:
  test:
    jobs:
      - test
