version: 2.1

jobs:
  test:
    docker: 
      - image: joshuaxong/racing-odds-scraper
    steps:
      - checkout
      - run: npm install
      - run: npm test
workflows:
  test:
    jobs:
      - test
