version: 2.1

jobs:
  test:
    docker: 
      - image: joshuaxong/racing-odds-scraper
    steps:
      - checkout
      - run: >
          apt-get update
          && apt-get install -y wget gnupg ca-certificates procps libxss1
          && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          && apt-get update
          && apt-get install -y google-chrome-stable
          && rm -rf /var/lib/apt/lists/*
          && wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh
          && chmod +x /usr/sbin/wait-for-it.sh
      - run: npm install
      - run: bash -c "cd ./node_modules/puppeteer && npm run install"
      - run: cd ../../ && npm run test
workflows:
  test:
    jobs:
      - test
