/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package racing.odds.server.app.services;

public class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
