/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package racing.odds.server.app;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
@RequestMapping(value = "/api/v0")
public class App {
  @Value("${spring.application.name}")
  private String name;

  @Value("${server.port}")
  private String port;

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
  }

  @RequestMapping(value = "/settings")
  public String port() {
    return String.format("Here are some of the settings ran by the server, port: %s", this.port);
  }
}
